# Generated by Django 5.0.6 on 2024-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="patientdischargedetails",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
